/**
 * Hand-curated content for town landing pages.
 *
 * Each entry is drafted by Claude Opus via `scripts/draft-town-content.ts`,
 * which pulls `docs/LOCAL-KNOWLEDGE-BASE.md` + `docs/PERSONAS.md` + the About
 * page voice as context, then reviewed and edited by Rob before commit.
 *
 * Voice rules (enforced by the draft script's system prompt):
 * - Reference real local businesses, owner names, and landmarks. No generic
 *   "explore the charming town" copy.
 * - Persona-targeted: each town speaks to at least one of Gary, Mia, Karen,
 *   Miguel, Jen by lived situation, not by name.
 * - No banned marketing phrases: "discover", "explore", "your gateway to",
 *   "nestled in the heart of", "charming", "hidden gem".
 * - Falsifiable specifics over vibes ("the post office closes at 4:30").
 * - No em dashes. SOUL.md voice rule. Use commas, periods, semicolons.
 *
 * To add a town: run `npx tsx scripts/draft-town-content.ts <slug>`, review
 * the printed draft, and paste it into this registry. Towns without an entry
 * here will 404 (intentional, we only ship pages with real content).
 */

import type { FaqEntry } from "@/lib/schema";

export interface TownContent {
  /** URL slug. Matches the dynamic route param. */
  slug: string;
  /** Canonical town name from CORRIDOR_TOWNS. */
  townName: string;
  /** <title> override. */
  metaTitle: string;
  /** Meta description. 150 to 160 chars. */
  metaDescription: string;
  /** Page H1. */
  h1: string;
  /** Single-line subhead beneath the H1. */
  subhead: string;
  /** Above-the-fold teaser. 1-2 sentences. Always visible. Highest AEO weight,
   * since snippet engines often quote the first ~1500 chars of a page. */
  introTeaser: string;
  /** Long-form intro paragraphs. 2 to 3 paragraphs, 300 to 500 words total,
   * drafted by Opus. Rendered inside a <details> behind a "Read more" toggle. */
  intro: string[];
  /** "If you're..." persona-targeted bullets (3 to 6 items). */
  personaNotes: string[];
  /** Falsifiable local facts: parking, hours, who's open in winter, etc. */
  worthKnowing: string[];
  /** Town-specific Q&A. 3 to 5 items. */
  faqs: FaqEntry[];
  /** YYYY-MM-DD. Surfaced as the page's "Last verified by Rob" stamp. */
  lastVerified: string;
  /**
   * Draft / pending verification. When true:
   * - page renders a visible "DRAFT" banner at the top
   * - metadata sets robots: noindex, nofollow
   * - sitemap.ts excludes the URL so Google doesn't crawl it
   * - lastVerified date is ignored in the byline (replaced with "Pending verification")
   * Set false (or omit) only after every fact on the page is sourced and confirmed.
   */
  draft?: boolean;
}

/**
 * Town content registry. Keyed by slug.
 *
 * Towns NOT in this map will 404. This is deliberate. Better to ship 1
 * great Murphys page than 9 templated stubs that get flagged for thin
 * content by the Helpful Content Update.
 */
export const TOWN_CONTENT: Record<string, TownContent> = {
  // Murphys: proof-of-voice draft generated by Opus (scripts/draft-town-content.ts)
  // and reviewed by Rob. Other 8 towns drop in here after the same workflow.
  murphys: {
    slug: "murphys",
    townName: "Murphys",
    // Published 2026-05-25 after Rob's review. Banner removed, sitemap includes the URL, search engines may index.
    metaTitle: "Murphys, CA Events: Wine, Live Music & Festivals | Hwy 4",
    metaDescription:
      "What's on in Murphys this week. Main Street tasting rooms, weekly Open Mic at the Irish Pub, Saturday farmers market, and Gold Rush history. Updated daily by a local.",
    h1: "What's happening in Murphys this week?",
    subhead:
      "Two dozen tasting rooms, weekly Open Mic at the Irish Pub, and a Main Street that runs on local-and-tourist time.",
    introTeaser:
      "Murphys is the wine country stop on the way up the 4. Fifteen minutes below Arnold, about an hour from Stockton, and the place most out-of-towners picture when they hear Calaveras.",
    intro: [
      "Main Street has roughly two dozen tasting rooms inside a walkable couple of blocks. Newsome Harlow at one end with the fire pit and the casual-locals crowd. Val du Vino is a personal favorite of mine for an easy afternoon flight. Hovey Winery in the historic Albert Michelson house, now known for Tempranillo, Albarino, and Verdelho (founder Chuck Hovey passed in 2019; the winery is run by a group of his close friends). Lavender Ridge, owned by Rich and Siri Gilpin since 2000, with cheese pairings and a lavender boutique attached. Hours vary by room: Newsome Harlow opens Mondays at noon, Ironstone is Friday through Sunday, Lavender Ridge and Hovey are daily. Parking is free if you can find it after 11am on a Saturday.",
      "What I tell people who haven't been: the food is better than the wine reputation suggests. Grounds, on Main since 1992, is where Chef/Owner River Klass cooks French-technique breakfast and dinner. He also owns Firewood, the wood-fired pizza spot down the block. V Restaurant tucked into the same building as Grounds (Suite L), opened by Michael and Melissa Ninos in 2004, is the most upscale room in the county. Thursday through Sunday, reservations matter. Both Grounds and V share an outdoor courtyard out back: protected from wind and sun, dog-friendly, one of our family's year-round go-to spots. Alchemy across the street is the unhurried beer-and-wine spot for lunch or dinner with a group. The Watering Hole on Big Trees Road has 40 draft beers, a serious bottle list, chef-driven pub food from owner Jason Wright, and a creek-side patio with a fire pit. Closed Wednesdays, which has burned me more than once.",
      "The Murphys Irish Pub is the Main Street music venue, though they're closed Monday and Tuesday. Open Mic is Wednesdays at 6pm. The rest of the week is a rotating calendar of bands, acoustic acts, and karaoke posted on murphysirishpubca.com. The Murphys Historic Hotel saloon dates to 1856 and claims to be the longest continuously operated hotel in California. Documented guests include Mark Twain, Ulysses S. Grant, John Jacob Astor, Horatio Alger Jr., and Charles 'Black Bart' Boles. It's more for the history than the music lineup, but it counts. Aria Bakery at 458 Main opens at 7am for cinnamon rolls and Temple Coffee espresso. Gold Country Roasters at 78 Scott Street, a block off Main, is the other morning ritual; their house roast is the Angels Camp Blend, and they close at 2:30pm. If you're doing one big day on Main Street, my standing recipe is: park once, coffee at Aria, three tasting rooms (Newsome Harlow, Lavender Ridge, Frog's Tooth), lunch at Alchemy, ice cream at Joma's, and you're loose enough to keep going.",
    ],
    personaNotes: [
      "You're driving up from the Bay or the Valley and want a Main Street worth the trip. Murphys is the corridor's headline town.",
      "You're staying in an Arnold cabin and want one day down the hill that doesn't feel like work. Wineries plus a real dinner.",
      "You're closing up at a winery and want to know what's still serving on Main Street after 9pm.",
      "You're hosting guests at a rental and need to send them somewhere walkable with food, wine, and Gold Rush history.",
      "You're bringing the dog and need a Main Street with patios that actually welcome them, not just tolerate them.",
      "You're a music regular and want to know what's at the Irish Pub tonight without scrolling Facebook.",
    ],
    worthKnowing: [
      "Main Street parking gets thin after 11am on weekends. There's a public lot behind the visitors center at 202 Main Street.",
      "Skip Uber and Lyft (they don't run up here). Murphy's Taxi is the local rideshare: 209.795.7777 for calls, 209.404.6229 for weekday texts only, owner Tim Vargas. Hours Mon-Thu 8am-6pm, Fri-Sat to 8pm (7pm Nov-May), Sundays by pre-booking only. This applies to every town on the 4.",
      "Most tasting rooms are walkable from each other. Ironstone Vineyards is a five-minute drive out Six Mile Road, open Friday through Sunday 11am to 5pm, with an amphitheater, wine caves, gardens, and Gold Leaf Bistro for brick-oven pizza. Their Heritage Museum is closed for renovations as of mid-2026.",
      "Indian Rock Vineyards is a five-minute drive past the Murphys Hotel at the far end of town. Pond, yard, calmer than Main Street. Worth the extra mile if you've already done the walking part.",
      "The Watering Hole is closed Wednesdays. The Irish Pub is closed Monday and Tuesday. Open Mic at the Pub is Wednesdays at 6pm.",
      "Aria Bakery opens at 7am. Their listed hours are Mon-Thu 7am to noon, Fri-Sun 7am to 3pm, but it's worth calling ahead for a Tuesday afternoon cinnamon roll.",
      "Gold Country Roasters' house blend is called the Angels Camp Blend, not the Murphys Blend. They're at 78 Scott Street, a block off Main, and close at 2:30pm.",
      "The Murphys Farmers Market runs Saturdays 9am to 1pm at Murphys Park, May through Thanksgiving. If somebody tells you Sundays, they're working from old info.",
      "Murphys Irish Day in March is the town's biggest street event. Get there early because Main Street fills up. Book Murphy's Taxi (209.795.7777) ahead if you need a ride back.",
      "Sierra Hills Market on E Highway 4 has the deli sandwiches locals actually pack for picnics. Better than the wine-bar charcuterie boards.",
      "Bear Valley is another 45 minutes east and roughly 5,000 feet higher. If somebody tells you Murphys is in the snow, they're confused about which town.",
    ],
    faqs: [
      {
        question: "What's the best night to see live music in Murphys?",
        answer:
          "The Murphys Irish Pub at 415 Main is the busiest live music room in town, though they're closed Monday and Tuesday. Wednesday is Open Mic at 6pm. The rest of the week rotates bands, acoustic acts, and karaoke; the current calendar is on murphysirishpubca.com. The Watering Hole runs a smaller program on weekends, and Stevenot Winery in Vallecito does summer weekend bands.",
      },
      {
        question: "How many wineries are actually on Main Street?",
        answer:
          "About 24 tasting rooms within walking distance of each other on or just off Main, with another handful out in Vallecito. The names locals send people to first: Newsome Harlow, Hovey, Lavender Ridge, Frog's Tooth, Gossamer Cellars. Ironstone Vineyards is the destination winery and worth its own afternoon, but it's a five-minute drive out Six Mile Road, not on Main Street.",
      },
      {
        question: "Where do locals eat in Murphys?",
        answer:
          "Grounds on Main, run by Chef/Owner River Klass since 1992, for breakfast and dinner that punches above its weight. Alchemy across the street for the deep beer-and-wine list and group meals. V Restaurant in the back of Grounds' building (Suite L), opened by Michael and Melissa Ninos in 2004, for special occasions and the most upscale room in the county. The Watering Hole on Big Trees Road for craft beer and pub food on a creek-side patio.",
      },
      {
        question: "Is Murphys family-friendly or more of a wine-tasting trip?",
        answer:
          "Both. Ironstone has the amphitheater, wine caves, gardens, and a brick-oven pizza spot (Gold Leaf Bistro). Joma's makes ice cream on Main Street, and Nelson's Candy a few doors down is a five-generation family candy shop, closed Tuesdays. Firewood does wood-fired pizza for the easy family dinner. The tasting rooms themselves are built around adults; the kid-friendly stuff is at the edges.",
      },
      {
        question: "Do I need a reservation for tasting rooms or restaurants?",
        answer:
          "On a quiet Wednesday no, on a Saturday or during Murphys Irish Day absolutely. V Restaurant takes reservations. Frog's Tooth recommends them. Most tasting rooms are walk-in, but parties of six or more should call ahead, especially November through April when hours thin out.",
      },
      {
        question: "Can I get around Murphys without a car?",
        answer:
          "Main Street itself is walkable end to end, about a 10-minute stroll past most of the tasting rooms and restaurants. For longer hops (Ironstone, Indian Rock, Vallecito, or back to your rental), use Murphy's Taxi: 209.795.7777 for calls, 209.404.6229 for weekday texts only. Owner Tim Vargas. Hours Mon-Thu 8am-6pm, Fri-Sat to 8pm (7pm Nov-May), Sundays by pre-booking only. There is no Uber or Lyft in Calaveras County.",
      },
    ],
    lastVerified: "2026-05-25",
  },
};

export function getTownContent(slug: string): TownContent | null {
  return TOWN_CONTENT[slug] ?? null;
}

/** Every town that has a content entry. Used for generateStaticParams so
 * drafts pre-render and are reachable for review. */
export function getAllTownSlugs(): string[] {
  return Object.keys(TOWN_CONTENT);
}

/** Only towns with verified content. Used for sitemap.xml so drafts are
 * not advertised to search engines. */
export function getPublishedTownSlugs(): string[] {
  return Object.entries(TOWN_CONTENT)
    .filter(([, c]) => !c.draft)
    .map(([slug]) => slug);
}
