"use server";

import { revalidatePath } from "next/cache";
import { SITE_URL } from "@/lib/constants";
import { failRedirect, flashRedirect } from "@/lib/admin/flash";

// "Run now" for the briefings. The chief-of-staff digest and growth memo are
// otherwise only generated by cron; this lets a human trigger one from the
// cockpit (the empty-state copy promised this button but it never existed).
// It calls the same CRON_SECRET-gated route the scheduler hits, so there is one
// generation path, not two. Read-only side effect: it writes one agent_runs row.
export async function runBriefing(formData: FormData) {
  const view = formData.get("view") === "growth" ? "growth" : "today";
  const route = view === "growth" ? "growth-memo" : "chief-of-staff";
  const dest = view === "growth" ? "/admin/briefings?view=growth" : "/admin/briefings";

  const secret = process.env.CRON_SECRET;
  if (!secret) failRedirect(dest, "CRON_SECRET is not set; cannot run by hand.");

  // Keep redirect() (which throws NEXT_REDIRECT) OUT of the try/catch, or the
  // catch would swallow it. Collect the outcome, then redirect.
  let ok = false;
  let message = "";
  try {
    const res = await fetch(`${SITE_URL}/api/agent/${route}`, {
      headers: { Authorization: `Bearer ${secret}` },
      cache: "no-store",
    });
    ok = res.ok;
    if (!ok) message = `Run failed (${res.status}). Check the logs.`;
  } catch (err) {
    message = `Run failed: ${err instanceof Error ? err.message : "network error"}`;
  }

  if (!ok) failRedirect(dest, message);

  revalidatePath("/admin/briefings");
  flashRedirect(dest, view === "growth" ? "Growth memo generated." : "Digest generated.");
}
